%YAML 1.2
---
# Default parameters for the Tracking program
# All parameters can be changed to accomodate user needs.
# All parameters can be changed at runtime with the appropriate config
User:
  name: Aquiles

Saving:
  auto_save: False
  directory: C:\data\nanoCET
  filename_video: Video.hdf5 # Can be the same filename for video and photo
  filename_photo: Snap.hdf5

GUI:
  length_waterfall: 100 # Total length of the Waterfall (lines)
  refresh_time: 100 # Refresh rate of the GUI (in ms)

Camera:
  camera: dummyCamera # the camera to use
  model: dummy
  exposure_time: 50 # Initial exposure time (in ms)
  binning_y: 1 # Binning
  binning_y: 1
  roi_x:
    - 0 # Leave at 0 for full camera
    - 0
  roi_y:
    - 0
    - 0
  background: '' # Full path to background file, or empty for none.

Tracking: # Not yet implemented, will show up in the config window
  param_1: 0
  param_2: 0